### ISSUE TITLE
Just want to say this is amazing

### ISSUE THREAD

**Issue by mxstbr** [zlypher/lol-events#20]
Thank you so much for building this. I live in my calendar, but constantly forget to check the LEC schedule and miss games I want to watch because I'm busy.

This repo has made me so much more likely to catch the games I want to watch live — it's seriously a godsend. Thank you for building this!

**Comment by mxstbr** [comment]
And you're from Vienna as well?! What are the chances! 🇦🇹 represent 😍

**Comment by League2EB** [comment]
thx all !!!!! @zlypher
